# Task 1 : Creating Arrays 

In [6]:
import numpy as np


array_1d = np.arange(1, 11)


array_2d = np.arange(1, 10).reshape(3, 3)


array_3d = np.random.rand(3, 5, 3)


for arr in [array_1d, array_2d, array_3d]:
    print("Shape:", arr.shape, "Size:", arr.size, "Data type:", arr.dtype)


Shape: (10,) Size: 10 Data type: int32
Shape: (3, 3) Size: 9 Data type: int32
Shape: (3, 5, 3) Size: 45 Data type: float64


# Task 2 : Array Indexing and Slicing

In [7]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print("First 3 elements:", data[:3])
print("Every alternate element:", data[::2])
print("Reversed array:", data[::-1])


First 3 elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


# Task 3 : Mathematical Operations 

In [8]:
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A + B:", A + B)
print("A - B:", A - B)
print("A * B:", A * B)
print("A / B:", A / B)

print("Dot product:", np.dot(A, B))

print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard Deviation of A:", np.std(A))
print("Variance of A:", np.var(A))

print("Max of B:", np.max(B), "at index", np.argmax(B))
print("Min of B:", np.min(B), "at index", np.argmin(B))


A + B: [25 34 22 18 17]
A - B: [  9  -2 -18  16   9]
A * B: [136 288  40  17  52]
A / B: [ 2.125       0.88888889  0.1        17.          3.25      ]
Dot product: 533
Mean of A: 13.0
Median of A: 16.0
Standard Deviation of A: 5.692099788303083
Variance of A: 32.4
Max of B: 20 at index 2
Min of B: 1 at index 3


# Task 4 : Reshaping and Transposing 

In [10]:
arr = np.arange(1, 13)

arr_2d = arr.reshape(4, 3)
arr_3d = arr.reshape(2, 2, 3)
arr_transposed = arr_2d.T

print("2D shape:", arr_2d.shape)
print("3D shape:", arr_3d.shape)
print("Transposed shape:", arr_transposed.shape)


2D shape: (4, 3)
3D shape: (2, 2, 3)
Transposed shape: (3, 4)


# Task 5 : Boolean Masking and Filtering 

In [11]:
data = np.random.randint(10, 51, 15)

print("Elements > 25:", data[data > 25])

data[data < 30] = 0
print("Replaced <30 with 0:", data)

count_div_5 = np.sum(data % 5 == 0)
print("Count of elements divisible by 5:", count_div_5)


Elements > 25: [38 49 36 39 32 34 34]
Replaced <30 with 0: [ 0  0 38  0  0 49 36 39 32  0  0 34  0  0 34]
Count of elements divisible by 5: 8


# Task 6: Working with Built-in Functions

In [12]:
linspace_array = np.linspace(0, 1, 10)
print("Equally spaced:", linspace_array)


identity = np.eye(4)
print("Identity matrix:\n", identity)


rand_arr = np.random.randint(1, 101, 20)
rand_arr.sort()
print("Sorted array:", rand_arr)
print("Top 5 largest elements:", rand_arr[-5:])


Equally spaced: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted array: [  8  12  18  21  23  24  25  27  30  45  51  62  66  68  74  74  79  79
  98 100]
Top 5 largest elements: [ 74  79  79  98 100]


# Task 7 : Generic 

In [1]:
import numpy as np
import time

start = time.time()


A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

#
C = A @ B


det = np.linalg.det(C)
print("Determinant:", det)


if np.abs(det) > 1e-10:  
    inverse = np.linalg.inv(C)
    print("Inverse calculated.")
else:
    print("Matrix is not invertible.")


end = time.time()


print("Time taken:", end - start, "seconds")


Determinant: -2.416625295746526e+49
Inverse calculated.
Time taken: 0.03172612190246582 seconds
